### ISSUE TITLE
Wrong line endings on main script getfile.sh

### ISSUE THREAD

**Issue by Carlos-SS-PMI** [gaddman/rundeck-getfile#2]
Hi!
This is a nice plugin, and really needed on Rundeck.

But when I've installed it failed like:
**/usr/bin/env: bash
: No existe el fichero o el directorio**

This mistake comes from line endings on "getfile.sh": they are DOS style, but they need to be Unix.
I've changed on my downloaded "rundeck-getfile.zip" file and really works well.

Can you do this quick fix?

Thanks!

**Comment by gaddman** [comment]
Thanks for reporting! Fixed by commit 87c50009ef218144bf160fb59202609b6e0eb66c
